name: "✅과제 요구사항 체크리스트"
description: 일정관리앱 과제 제출 전 요구사항을 확인하는 체크리스트입니다.
title: "[Lv1] 일정관리앱 기본 기능"
labels: ''
assignees: soo59599

body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 목표
        - 사용자가 일정을 등록, 조회, 삭제할 수 있어야 한다  
        - Spring Boot, JPA, RESTful API를 활용하여 구현한다  
        - 일정은 제목, 내용, 날짜 정보를 포함해야 하며, 날짜 순 정렬이 가능해야 한다

        > 과제 기준일: `2025-08-04`  
        > 작성자: `@soo59599`  

  - type: checkboxes
    id: features
    attributes:
      label: 💻 기능 구현
      description: 필수 및 선택 기능 구현 여부를 체크해주세요.
      options:
        - label: 일정 등록 기능이 정상적으로 동작함
        - label: 일정 조회 기능이 정상적으로 동작함
        - label: 일정 삭제 기능이 정상적으로 동작함
        - label: 날짜 기준 정렬이 정상적으로 동작함
        - label: (선택) 일정 수정 기능이 동작함

  - type: checkboxes
    id: submission
    attributes:
      label: 💬 메모 & 회고
      description: 제출과 회고 관련 사항을 체크해주세요.
      options:
        - label: 제출 마감일 이전에 업로드 완료
        - label: 과제 제출 링크 또는 PDF 포함됨
        - label: 구현 중 어려웠던 점 또는 느낀 점 기록함
