name: "✅ 일정관리앱 과제 체크리스트"
description: 일정관리앱 과제 제출 전 요구사항을 확인하는 체크리스트입니다.
title: "[Lv1] 일정관리앱 기본 기능"
labels: ["과제"]
assignees:
  - soo59599

body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 목표
        - 사용자가 일정을 추가, 수정, 삭제할 수 있어야 한다
        - `Spring Boot`, `JPA`, `Thymeleaf`, `MySQL`을 활용한다
        - 프로그램이 정상적으로 시작되고 종료되어야 한다

  - type: checkboxes
    attributes:
      label: 💻 기능 구현
      options:
        - label: 일정 추가 기능이 정상적으로 동작함
        - label: 일정 수정 기능이 정상적으로 동작함
        - label: 일정 삭제 기능이 정상적으로 동작함
        - label: 일정 단건 조회 기능이 정상적으로 동작함
        - label: 일정 전체 조회 기능이 정상적으로 동작함

  - type: checkboxes
    attributes:
      label: 💬 메모 & 회고
      options:
        - label: 제출 마감일 이전에 업로드 완료
        - label: 과제 제출 링크 또는 PDF 포함됨

  - type: markdown
    attributes:
      value: |
        > 과제 기한: `2025-08-04`  
        > 작성자: `@soo59599`
